Update launcher

diff --git a/Installer-SH/installer-data/program_files/launcher b/Installer-SH/installer-data/program_files/launcher
--- a/Installer-SH/installer-data/program_files/launcher
+++ b/Installer-SH/installer-data/program_files/launcher
@@ -1,32 +1,34 @@
 #!/usr/bin/env bash
-# Script version 1.0
-# This can help avoid application version conflicts, but requires special preparation.
-# WARNING! This is not intended for applications that are installed in system mode.
-# WARNING! This is an experimental feature.
+# LICENSE for this script is at the end of this file
 #
+# The launcher is designed to simplify the launch of Linux applications and move the home directory
+# to avoid conflicts between different versions of the same application.
 
 Path_To_Script="$( dirname "$(readlink -f "$0")")"
+UserDataFolder="$Path_To_Script/userdata"
+ProgramFolder="$Path_To_Script/program"
+ExecutableFolder="$ProgramFolder"
+ExecutableFile="$ExecutableFolder/application-one"
 
-export PATH="$PATH:$Path_To_Script/program"
-export HOME="$Path_To_Script/userdata"
+export PATH="$PATH:$ExecutableFolder" # Use ":" for separation
+export HOME="$UserDataFolder"
 
-export XDG_DATA_HOME="$HOME/.local/share"
-export XDG_STATE_HOME="$HOME/.local/state"
-export XDG_CONFIG_HOME="$HOME/.config"
-export XDG_CACHE_HOME="$HOME/.cache"
+export HOMECONFIGS="$UserDataFolder"
+export XDG_DATA_HOME="$HOMECONFIGS/.local/share"
+export XDG_STATE_HOME="$HOMECONFIGS/.local/state"
+export XDG_CONFIG_HOME="$HOMECONFIGS/.config"
+export XDG_CACHE_HOME="$HOMECONFIGS/.cache"
 
-application_exec="$Path_To_Script/program/application-one"
+if ! [[ -x "$ExecutableFile" ]]; then if ! chmod +x "$ExecutableFile"; then echo "chmod error"; fi; fi
 
-if ! [[ -x "$application_exec" ]]; then
-	if ! chmod +x "$application_exec"; then echo "chmod error"; fi
-fi
+cd "$ExecutableFolder"
 
-"$application_exec" "$@"
+"$ExecutableFile" "$@"
 
 exit_code="$?"
 
 if [[ "$exit_code" != "0" ]]; then
-	StringMessage="bash -c \"echo \"-\"; echo \"$application_exec\"; echo \"-\"; echo \"WARNING!\ EXIT\ CODE\ -\ $exit_code\"; echo \"The\ program\ has\ terminated\ incorrectly!\"; echo \"Is\ the\ program\ incompatible\ with\ the\ current\ OS?\"; echo \"Does\ the\ program\ contain\ errors?\"; read pause\""
+	StringMessage="bash -c \"echo \"-\"; echo \"$ExecutableFile\"; echo \"-\"; echo \"WARNING!\ EXIT\ CODE\ -\ $exit_code\"; echo \"The\ program\ has\ terminated\ incorrectly!\"; echo \"Is\ the\ program\ incompatible\ with\ the\ current\ OS?\"; echo \"Does\ the\ program\ contain\ errors?\"; read pause\""
 	
 	terminal_executable="x-terminal-emulator"
 	if ! type "x-terminal-emulator" &> /dev/null; then
@@ -39,3 +41,25 @@ if [[ "$exit_code" != "0" ]]; then
 	
 	$terminal_executable -e "$StringMessage"
 fi
+
+# MIT License
+#
+# Copyright (c) 2025 Chimbal
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# SOFTWARE.
