check exe rigths

diff --git a/Installer-SH/installer-data/program_files/launcher b/Installer-SH/installer-data/program_files/launcher
--- a/Installer-SH/installer-data/program_files/launcher
+++ b/Installer-SH/installer-data/program_files/launcher
@@ -17,6 +17,10 @@ export XDG_CACHE_HOME="$HOME/.cache"
 
 application_exec="$Path_To_Script/program/application-one"
 
+if ! [[ -x "$application_exec" ]]; then
+	if ! chmod +x "$application_exec"; then echo "chmod error"; fi
+fi
+
 "$application_exec" "$@"
 
 exit_code="$?"
diff --git a/Installer-SH/installer-data/program_files/launcher-two b/Installer-SH/installer-data/program_files/launcher-two
--- a/Installer-SH/installer-data/program_files/launcher-two
+++ b/Installer-SH/installer-data/program_files/launcher-two
@@ -19,6 +19,10 @@ application_exec="$Path_To_Script/program-two/application-two"
 
 "$application_exec" "$@"
 
+if ! [[ -x "$application_exec" ]]; then
+	if ! chmod +x "$application_exec"; then echo "chmod error"; fi
+fi
+
 exit_code="$?"
 
 if [[ "$exit_code" != "0" ]]; then
